graphile/graphile-engine

packages/graphql-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphql-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
packages/graphql-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphql-build/README.md
packages/graphql-build/src/SchemaBuilder.js
packages/graphql-build/src/makeNewBuild.js
packages/graphql-build/src/plugins/ClientMutationIdDescriptionPlugin.js

This moves `field` to `GraphQLObjectType:fields:field` (and `inputField` `GraphQLInputObjectType:fields:field`).
I decided not to call it `GraphQLObjectType:field` because it's too visually similar to `GraphQLObjectType:fields`; it's also more accurate from a hierarchy point of view.
This is a breaking change.

breaking(hooks): rename 'field'/'inputField' hooks into parent namespace

---

packages/postgraphql-build/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphql-build/__tests__/integration/schema.test.js
packages/postgraphql-build/__tests__/printSchemaOrdered.js

So we can validate fields that have been added/removed when reviewing Pull Requests. Uses alphabetical schema ordering so that diffs are easier to read.

test(schema): add snapshots for generated schema

---

packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap

Fixes #51 - RLS policy may prevent fetching the relation (even if references are non-null) so we must account for this.

fix(relations): make forward relations nullable

---

packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build/package.json
packages/graphile-build/src/makeNewBuild.js
packages/graphile-build/src/plugins/StandardTypesPlugin.js

We don't want two conflicting implementations of JSON (one string, one object).

chore: remove JSON/UUID types from core

---

packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/procedure-query.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

fix(procedures): support procedures returning setof composite

---

packages/graphile-build-pg/src/inflections.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js

The inflector function `singleRelationByKeys` does not only change the names for related elements on an object, e.g.
```graphql
user {
postsByUserId { // <--
....
}
}
```
but also for queries that are based on unique columns, e.g. `userByEmail()`.
This PR splits it up into two functions.
Please note that I was not able to build this locally, the changes seemed to be ignored. 
I followed the instructions from the README.md, but had to run `yarn` in the directory of all packages.

feat(inflector): split rowByUniqueKeys from singleRelationByKeys

---

packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/postgraphile-core/__tests__/fixtures/mutations/mutation-delete-error.graphql
packages/postgraphile-core/__tests__/fixtures/mutations/mutation-delete.graphql
packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Wraps each mutation in a transaction, automatically rolling back so that a) results of previous mutations are not invalidated (see #75) and b) future mutations are not prevented.
Fixes postgraphql/postgraphql#563
Fixes #75

fix(mutations): nullable payloads, rollback individual mutations on error

---

packages/graphile-build-pg/src/plugins/makeProcField.js
packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap

fix(procedures): fix arg refs where SQL and GraphQL field names differ

---

packages/graphile-build-pg/src/QueryBuilder.js

see #88 
I have not found a way to get access to the QueryBuilder yet from a orderby callback spec. maybe some sleep will help, meanwhile. I could complete my task with this patch to the QueryBuilder

give the QueryBuilder to callback function in callIfNecessary

---

packages/graphile-build-pg/res/introspection-query.sql
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Fixes https://github.com/graphile/graphile-build/issues/83

Solve some of the array of custom type issues

---

packages/graphile-build-pg/res/introspection-query.sql
packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/queryFromResolveData.js
packages/postgraphile-core/__tests__/fixtures/queries/view.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
packages/postgraphile-core/src/index.js

Postgres views do not support constraints like the primary key constraint. graphile uses the primary key constraint to set the default orderBy which is used to create the unique cursors. The view cursors end up working only when the graphql orderBy parameter is always unique.
* Add pg class relkind to introspection query
* Add check for pg class relkind view and uniqueId attribute.
* In the case of no primary key and no configured view unique key then default to row number. ref #104
NOTE: ~~When creating the view in postgres view one of the columns needs to be named specifically **uniqueId**. e.g. `create view testview as select id as "uniqueId", name from device;`~~ If viewUniqueKey option is set to a column then it will be used.
Added two test queries w/ a configured viewUniqueKey and …

Improve pg view cursor support

---

packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build-pg/src/plugins/viaTemporaryTable.js
packages/postgraphile-core/__tests__/fixtures/mutations/mutation-create.graphql
packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

I added some tests for the apparent issue with `viaTemporaryTable` . While doing that I found another  `malformed record literal` issue related with the `comptypes`. I added a test for that on `mutation-create`.
As per our discussion we found this other [issue](https://github.com/postgraphql/postgraphql/blob/607f6629986735139e2b77d5a9b1143846c4f691/src/postgraphql/withPostGraphQLContext.ts#L218-L230) where the queries are logged before execution, so if the second query never gets logged then it's never ran and thus the error does not exist there.

Issues with custom types / malformed record literal

---

packages/postgraphile-core/README.md

With these changes, the approach in this example can be executed (assuming the proper schema is already in place).
FYI, there is a very similar example in graphile.github.io/src/pages/graphile-build-pg/security.md, so if/when this is merged, I can clean up that file as well.
That said.. is there any reason you're not using the forum example schema here?  In general, I think the examples would be a lot more useful if they could be run against a known schema.

Fix example in README.md

---

packages/graphile-build-pg/src/plugins/PageInfoStartEndCursor.js
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build/__tests__/fieldData.test.js
packages/graphile-build/__tests__/watch.test.js
packages/graphile-build/src/extend.js
packages/graphile-build/src/makeNewBuild.js
packages/graphile-build/src/plugins/NodePlugin.js
packages/graphile-build/src/plugins/StandardTypesPlugin.js

Fixes https://github.com/postgraphql/postgraphql/issues/590
Enables https://github.com/postgraphql/postgraphql/issues/473
This PR adds a lot more consistency to `fieldWithHook`, but in doing so it includes 🔥 BREAKING CHANGES🔥  for anyone who's using third-party plugins!
- The third argument (`fieldScope`) to `fieldWithHooks` is now required
- `fieldScope` may *no longer* overwrite the parent object's scope - so ⚠️  things like `pgIntrospection` have changed to `pgFieldIntrospection` ⚠️  when they specifically relate to the field (thus the `pgIntrospection` of the parent object is still available)
- `isPgConnectionField` has changed to `isPgFieldConnection` (everywhere you've used `isPgFieldConnection` you'll also need to change `pgIntrospection` for `pgFieldIntrospection` also

fix(fields): make fieldWithHooks much more consistent

---

packages/graphile-build-pg/src/plugins/makeProcField.js
packages/postgraphile-core/__tests__/fixtures/queries/procedure-query.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Have added a bit of text explaining this here:
https://github.com/postgraphql/postgraphql/wiki/Known-issues#omitting-function-argument-that-have-defaults---use-named-function-parameters
Basically, so long as the arguments to a function are named we can omit those with defaults just fine. If the arguments with defaults are NOT named we pass null in many cases which is not what you want, but I couldn't find a workaround.
Fixes #87

fix(procs): Functions no longer passed null for missing arguments (unless necessary)

---

packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

They don't (because no indexes get exported, only constraints - and constraints can't be partial), but this will enforce that's always the case.

chore(test): Assert that partial indexes don't get exported

---

packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/empty-array.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Adds a failing test for empty arrays being resolved to null, causing an error to be thrown when the array column is `not null` in postgres.
postgraphql/postgraphql#648

fix(sql): don't return null for empty arrays

---

packages/graphile-build-pg/src/plugins/PgTypesPlugin.js

Fixes #134 
Not sure if this is the best solution, gunna think on it for a bit.

fix(getTypeByName): register default types like JSON earlier

---

packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js
packages/postgraphile-core/__tests__/fixtures/queries/connections.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap

This PR changes the orderBy enum type to a GraphQLList.  As discussed in https://github.com/graphile/graphile-build/issues/81#issuecomment-351522129, GraphQLList types can accept either a single value or an array, so this should be a non-breaking change.

feat(graphile-build-pg): Change connection orderBy argument to GraphQLList

---

packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgOrderAllColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js

This will allow plugins to "enhance" pgColumnFilter over and above what the user provides.
For example, the user might say `pgColumnFilter: attr => attr.name !== 'secret'` to hide a secret column
But someone could write a plugin that would then enhance this pgColumnFilter to also hide any fields beginning with `_`; something like:
```js
function PgHideUnderscoresPlugin(builder) {
builder.hook("build", build => {
const previousPgColumnFilter = build.pgColumnFilter;
return {
...build,
pgColumnFilter(attr, ...rest) {
if (attr.name[0] === '_') {
return false;
} else if (previousPgColumnFilter) {
return previousPgColumnFilter(attr, ...rest);
} else {
return true;
}
}
};
});
}
```
⚠️  Code example was written off the top of my head direct into the GitHub comment box - it might not even compile, …

chore(refactor): move pgColumnFilter onto build

---

packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build/src/SchemaBuilder.js
packages/graphile-build/src/makeNewBuild.js
packages/postgraphile-core/src/index.js

Fixes #118
This PR allows you to wrap expensive functions during plugin initialisation with `persistentMemoizeWithKey` (as you can see in the PgIntrospectionPlugin). By default this doesn't do much, but in `postgraphile-core` we enable these results to be written out to a JSON file so that they can be loaded on production (or wherever) to reduce startup time. Particularly useful for people using Lambda.
Plugins that utilise this are required to ensure that the cache keys they use:
- are globally unique (suggest you prefix the cache key with the name of the plugin)
- contain everything required to ensure that the cache will be invalidated if the logic changes (e.g. you might use the plugin version, in some cases you might need to combine this with the version numbers of other plugins also) …

feat(cache): enable memoizing time-intensive tasks to disk

---

packages/graphile-build-pg/src/inflections.js
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

🔥  Breaking change if you have any tables that have names that end with "input(s)" or "patch(s)".
Fixes https://github.com/postgraphql/postgraphql/issues/647
Automatically add 'Record' to tables that end in the reserved words 'Input' and 'Patch' to avoid them clashing with other tables that share the same prefix.
Even if they don't clash *right now* there's a risk that they will clash in future; e.g. if you create the table `foo_bar_input` then creating `FooBarInput` and `FooBarInputInput` and `FooBarInputPatch` is fine... But if you later add the table `foo_bar` then `FooBarInput` will clash. So renaming the tables up front means that whether or not you add that table later it'll still be fine without breaking existing functionality.
Tables named like `inputs` and `patchs` should not be …

fix(clash): Auto-rename clashing _input/_patch tables

---

packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build/src/SchemaBuilder.js
packages/graphile-build/src/makeNewBuild.js
packages/postgraphile-core/__tests__/fixtures/mutations/mutation-update.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap

Fixes https://github.com/postgraphql/postgraphql/issues/664
🔥 BREAKING CHANGE: mutation payloads now support array `orderBy` to match collections. This may cause problems for people using Relay

fix(mutations): Fix null cursor on mutations, make orderBy an array too

---

packages/graphile-build-pg/src/QueryBuilder.js

Before:
`select to_json(json_build_array('primary_key_asc'::text, json_build_array(__local_0__."id"))) as "__order_primary_key_asc", to_json(json_build_array(__local_0__."id")) as "__identifiers", to_json((__local_0__."name")) as "name", to_json(json_build_array('primary_key_desc'::text, json_build_array(__local_0__."id"))) as "__order_prima
ry_key_desc", to_json(json_build_array(__local_0__."id")) as "__identifiers", to_json((__local_0__."name")) as "name", to_json(json_build_array('id_asc'::text, json_build_array(__local_0__."id", __local_0__."id"))) as "__order_id_asc", to_json(json_build_array(__local_0__."id")) as "__identifiers", to_json((__local_0__."name")) as "name", to_json(json_build_arra
y('id_desc'::text, json_build_array(__local_0__."id", __local_0__."id"))) as …

fix(sql): reduce redundancy in select statements

---

.travis.yml
package.json
packages/graphile-build-pg/package.json
yarn.lock

To use the latest `pg` you need to be running node v4.5 or higher; but you can force pg to an earlier version if you need so this isn't a breaking change.

chore(deps): expand 'pg' support range to '>=6.1 <8'

---

packages/graphile-build-pg/src/inflections.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js

This PR wraps all inflectors with a function that asserts that the result of the inflector is a non-empty string. This should help track down issues like #169 faster by throwing the error at inflection time whilst the schema is being built rather than during the validation phase once the schema has already been built.
Fixes #169

feat(errors): Check inflectors give non-empty string

---

packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/one-to-one-backward.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/integration/schema.test.js
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
packages/postgraphile-core/src/index.js

This'll add one-to-one relationships - i.e. where a remote table references the current table using a *unique* column.
~~This will be a breaking change (the last planned one before the release of v4), but~~ I'll be adding a flag to allow you to go enable the old behaviour instead. (Actually this should probably be a dual flag so that you can export the old interface as deprecated along with the new interface which isn't?)
This won't be a breaking change because the default for the flag will be to deprecate the old relations (but still support them).
Fixes postgraphql/postgraphql#432
Fixes postgraphql/postgraphql#283
Fixes postgraphql/postgraphql#123

feat: one-to-one relationships

---

.babelrc
package.json
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/badlyBehavedFunction.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
packages/postgraphile-core/src/index.js
yarn.lock

Add object rest/spread support to babel 🎉 
Tweak/add some comments.
Add `pgForbidSetofFunctionsToReturnNull` / `--no-badly-behaved-functions` option (default: ON ✅ ) - this is a breaking change **if** you return nulls in the middle of `setof` functions (why would you do that?!! 😖 ) - e.g.
```sql
create function c.badly_behaved_function() returns setof c.person as $$
begin
return query select * from c.person order by id asc limit 1;
return next null; -- < Returning null in the middle of a function is BAD, mmmmkay?
return query select * from c.person order by id desc limit 1;
end;
$$ language plpgsql stable;
```
This makes a load of stuff non-null so turning this option off (with `--badly-behaved-functions`) is a breaking change - do it early if you need it!

fix(compatibility): v3 compatibility tweaks

---

packages/graphile-build-pg/package.json
yarn.lock

Squeezes out a little additional performance through micro-optimisations to pg-sql2
(I can't believe I spent 2 hours on this instead of sleeping... Oh well, fetching no data [from a fairly simple query](https://github.com/graphile/postgraphile_changes/blob/fff2ef4cf8eacfe1ca29a40363bb665a36efebbd/graphql/PopularThreads.graphql) is now about 60% faster... Just think of all the electrons I'm no longer inconveniencing!)

perf(sql): upgrade pg-sql2

---

packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/integration/schema.test.js
packages/postgraphile-core/src/index.js

- 'badlyBehavedFunctions' is too judgemental
- defaulting to *allow* setof functions to return nulls will reduce the schemas that will cause errors
- if the nullables bother you you can turn it off with a single option as a **non-breaking change**
I never released the old version under the old name, so this is not a breaking change.

chore(functions): renamed nullable setof function option, changed default

---

packages/postgraphile-core/src/index.js

Doesn't change any functionality, all the same stuff is still exported.

chore(rename): postgraphql -> postgraphile

---

packages/graphile-build-pg/res/introspection-query.sql

Since PostgreSQL 9.1 `standard_conforming_strings` has defaulted to `on`; however someone raised an issue in the gitter that PostGraphile wasn't successfully introspecting their database, but no errors were output. PostGraphQL v3 worked fine, so I could simply do a diff of the introspection queries. When running the introspection query the following errors were raised:
```
WARNING:  nonstandard use of escape in a string literal
LINE 61:       pro.proname not like '\_\_%' and
^
HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
WARNING:  nonstandard use of escape in a string literal
LINE 104:       rel.relname not like '\_\_%' and
^
HINT:  Use the escape string syntax for escapes, e.g., E'\r\n'.
WARNING:  nonstandard use of escape in a string literal
LINE 127: …
```

fix(sql): still introspect when standard_conforming_strings is off

---

packages/graphile-build-pg/res/introspection-query.sql

After upgrading a database using `pg_upgrade`, it's possible for stale entries in `pg_description` to exist. These refer to an old `pg_class` system catalog. These need to be filtered out by only including descriptions related to the current `pg_class` system catalog.
---
This is a fix I'm using after upgrading my Postgres 9.6 to Postgres 10.3 RDS instance via AWS (which uses pg_upgrade). It seems that pg_upgrade left behind a stale record in pg_description, which caused this error:
```
Error: Type 'NotesOrderBy' has already been registered! 
at Object.newWithHooks (/app/node_modules/graphile-build/src/makeNewBuild.js:650:17) 
at introspectionResultsByKind.class.filter.filter.forEach.table (/app/node_modules/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js:28:11) 
at Array.forEach …
```

fix: gracefully handle stale pg_catalog.pg_description

---

lerna.json
package.json
packages/graphile-build-pg/package.json
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/queryFromResolveData.js
packages/graphile-build/package.json
packages/graphile/package.json
packages/graphql-parse-resolve-info/package.json
packages/graphql-parse-resolve-info/src/index.js
packages/postgraphile-core/__tests__/fixtures/queries/simple-collections.graphql
packages/postgraphile-core/__tests__/fixtures/queries/simple-procedure-computed-fields.graphql
packages/postgraphile-core/__tests__/fixtures/queries/simple-procedure-query.graphql
packages/postgraphile-core/__tests__/fixtures/queries/simple-relations-head-tail.graphql
packages/postgraphile-core/__tests__/fixtures/queries/simple-relations-tail-head.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/simple-collections.test.js
packages/postgraphile-core/package.json
packages/postgraphile-core/src/index.js
yarn.lock

This adds a way to get lists of table rows without using Relay-compatible pagination - it effectively flattens the requests a bit.
e.g. this:
```graphql
{
allAlbumsList(condition: {artistId: 127}) {
id
title
tracksByAlbumIdList {
id
name
genreByGenreId {
name
}
}
}
}
```
instead of this:
```graphql
{
allAlbums(condition: {artistId: 127}) {
nodes {
id
title
tracksByAlbumId {
nodes {
id
name
genreByGenreId {
name
}
}
}
}
}
}
```
The "simple collections" support arguments `first`, `offset`, `condition` and `orderBy` like connections but do NOT support `before`, `after` or `last` because there's no access to cursors in the result set.
Simple collections are significantly lighter on server resources than relay connections.

feat(collections): add "simple collections"

---

packages/graphile-build-pg/src/plugins/PgTypesPlugin.js

This is to fix a bug where the negative sign is lost for money types.

Update parseMoney to handle negative values

---

packages/graphile-build-pg/package.json
packages/graphile-build-pg/src/GraphQLJSON.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build/package.json
packages/graphql-parse-resolve-info/package.json
packages/postgraphile-core/package.json

We should just use graphql off the build object to avoid version conflicts.

chore(graphile-build-pg): Remove GraphQL require

---

packages/graphile-build-pg/res/introspection-query.sql
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
packages/postgraphile-core/src/index.js

We now auto-filter functions/tables from extensions; this is technically a breaking change but I don't think many people were using this deliberately. You can go back to the old functionality with the CLI flag `--include-extension-resources`
---
[pg_attribute](https://www.postgresql.org/docs/10/static/catalog-pg-attribute.html) contains a field `atttypmod` which is a modifier for the type of a column, for example your column could be a `decimal`; but it could be `decimal(3,2)`. This `atttypmod` is where this distinction is stored (or `-1` if there is no subtype).
So we really need this in our modelling. Annoyingly this means that I've had to rebuild all the code that assumes we can do things based on type alone.
I've managed to do all these changes whilst maintaining backwards …

feat(pg): introspection of subtypes, exclude extension resources

---

packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/rbac.test.js
packages/postgraphile-core/__tests__/kitchen-sink-permissions.sql
packages/postgraphile-core/scripts/test

Previously tables that did `grant select(col1, col2) to role_name` would be excluded unless `--ignore-rbac` was enabled.

fix(rbac): don't exclude tables that use column-based select permissions

---

packages/graphile-build/src/index.js
packages/graphile-utils/__tests__/ExtendSchemaPlugin.test.js
packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin.test.js.snap
packages/graphile-utils/src/makeExtendSchemaPlugin.js

feat(utils): can define `subscribe` along with `resolve`

---

packages/postgraphile-core/__tests__/integration/schema/rbac.test.js
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
packages/postgraphile-core/src/index.js

Because it turns out some people use PostGraphile in interesting ways (e.g. defining and/or granting permissions after the server starts) this would be too much of a breaking change.

fix(rbac): revert default to ignoring RBAC

---

packages/graphile-build-pg/src/omit.js
packages/graphile-build/src/SchemaBuilder.js
packages/graphile-build/src/makeNewBuild.js
packages/graphile-build/src/swallowError.js

- Does not allow errors building `Query` to be swallowed
- Increases length of error snippets
- Improves wording of `@omit` error message relating to read dependency
Fixes graphile/postgraphile#813

fix(errors): More explicit error on schema build fail

---

packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/rbac.basic.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-permissions.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Fixes https://github.com/graphile/postgraphile/issues/812
If you define a type in a non-exposed schema, or define a type but don't grant access to it, then that type will generally not appear in your schema (if `ignoreRBAC: false`). If it does appear, chances are it's been pulled in by a SQL function or similar; if this is the case then pulling it through with no columns doesn't make any sense (and if there's no PK it can cause a crash as the type now has no fields). This PR adds attributes back on tables that haven't been granted *any* read permissions.

fix(rbac): allow exposing hidden types when sensible

---

packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/makeProcField.js

This allows plugins to get a reference to the parent builder so they can get the parent table name (for example) enabling them to add additional where clauses or whatever is necessary.
The motivation for this was so that I can add an 'INHERIT' option to my [PgOmitArchived](https://gist.github.com/benjie/5481c00e5847d82c1b4e9988eee6092e) plugin - this way if the parent record is archived then we can include archived children; otherwise if the parent is not archived then we omit archived children. I'm sure there's a lot more powerful uses it can be put to though 👍
- Refactored so all query builder references are `queryBuilder` (or `innerQueryBuilder` or whatever) - rather than using lazy `builder` name in some places
- Added a scope boolean to singular backward relations so they can be …

feat(query-builder): reference parent query builder on child

---

packages/graphile-utils/__tests__/ExtendSchemaPlugin.test.js
packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin.test.js.snap
packages/graphile-utils/src/makeExtendSchemaPlugin.js

I want support for enum types, so that I can extend the GraphQL schema to include enums. I'm fairly unfamiliar with this code base, so any guidance here would be appreciated.

feat(makeExtendSchemaPlugin): add support for enum

---

packages/graphile-build-pg/src/QueryBuilder.js
packages/postgraphile-core/__tests__/fixtures/queries/longAliases.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap

Fixes #268; previously only long aliases whose sha1sum began with a letter passed 😳

fix(graphql): handle all long aliases

---

package.json
packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
packages/graphile-utils/__tests__/utils-schema.sql
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

e.g.:
typeDefs:
```graphql
extend type MyTable {
fieldFromExternalSource: Whatever @requires(columns: ["id", "external_source_id"])
}
```
resolvers (note that the columns are converted to fields, so the case changes):
```js
{ MyTable: {
fieldFromExternalSource({id, externalSourceId}) {
// return fetch(`http://example.com/${externalSourceId}`)...
}
}}
```
Guarantees that the requested columns exist on the result set.

feat(utils): add `@requires(columns: [...])` directive

---

packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/unique-foreign-keys.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

We already recognise unique single-key relations and use a single relation (rather than a connection) for these. This PR extends that to multi-key relations that are unique (caveat: the unique constraint and the foreign key constraint must specify the columns in the same order).
This is not a breaking change (unless you have multi-key unique relations and use `--legacy-relations omit`, in which case I'm sure I would have heard about this earlier) because the old connection is still generated, it's just marked as deprecated.
Thanks to @charlescrain for bringing this to my attention on Gitter:
https://gitter.im/graphile/postgraphile?at=5b99af58d655361f76ef76ca

feat(pg): Recognise unique multi-key relations

---

packages/graphile-build-pg/src/withPgClient.js

As seen in the [docs](https://node-postgres.com/api/client), `pg` also accepts an object as the configuration:
```js
type pgConfigObject = {
user?: string, // default process.env.PGUSER || process.env.USER
password?: string, //default process.env.PGPASSWORD
database?: string, // default process.env.PGDATABASE || process.env.USER
port?: number, // default process.env.PGPORT
connectionString?: string, // e.g. postgres://user:password@host:5432/database
ssl?: any, // passed directly to node.TLSSocket
types?: any, // custom type parsers
statement_timeout?: number, // number of milliseconds before a query will time out default is no timeout
}
```
All the fields are entirely optional, would be filled with the env variables if available:
> Every field of the config object is entirely optional. A …

fix: Improve error message for invalid pg configurations

---

packages/graphile-build-pg/src/queryFromResolveData.js
packages/graphile-utils/src/index.ts
packages/graphile-utils/src/makePluginByCombiningPlugins.ts

`withBuilder` is used to set up some context, e.g. `innerQueryBuilder.parentQueryBuilder = queryBuilder`; but if you don't do this before calling the callbacks in `resolveData.pgQuery` then there's little point doing it.

fix(sql): queryFromResolveData call withBuilder before resolveData.pgQuery

---

packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
packages/graphile-build-pg/src/plugins/debugSql.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/plugins/viaTemporaryTable.js

When using `DEBUG="graphile-build-pg:sql"`, SQL will now be output formatted, with the the various `__local_#__` entries colour coded. We also no-longer prepend `graphile-build-pg:sql` to every line in the SQL statement. This makes debugging a lot easier!
Before:
After:
<details>
<summary>GraphQL Query</summary>
```graphql
query {
allPeople(first: 3, offset: 1) {
nodes {
nodeId
id
name
email
createdAt
postsByAuthorId(orderBy:PRIMARY_KEY_DESC, first:1) {
nodes {
nodeId
id
headline
body
author: personByAuthorId {
nodeId
id
name
}
}
}
}
}
}
```
</details>

feat(debug): enhance SQL debugging

---

packages/graphile-build/package.json

fix(deps): add chalk as explicit dependency of graphile-build

---

packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build/src/plugins/NodePlugin.js

If you want to add nodeId hooks, it is necesssary to have hooks on:
- nodeId creation (ok because getNodeIdForTypeAndIdentifiers is used everywhere)
- nodeId read (not ok because getTypeAndIdentifiersFromNodeId is duplicated twice)

do not duplicate getTypeAndIdentifiersFromNodeId code

---

packages/graphile-build-pg/src/QueryBuilder.d.ts
packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgColumnDeprecationPlugin.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

This is some minor cleanup following PRs https://github.com/graphile/graphile-engine/pull/332 and https://github.com/graphile/graphile-engine/pull/340

chore: cleanup function deprecation and nullsFirst features

---

package.json
packages/graphile-build-pg/package.json
yarn.lock

This resolves some peer dependency warnings when using GraphQL v14.
Changelogs:
https://github.com/excitement-engineer/graphql-iso-date/releases
https://github.com/apollographql/eslint-plugin-graphql/blob/master/CHANGELOG.md

chore: upgrade deps to support GraphQL v14

---

packages/graphile-build/src/SchemaBuilder.d.ts
packages/graphile-build/src/SchemaBuilder.js
packages/graphile-utils/__tests__/makeProcessSchemaPlugin.test.js
packages/graphile-utils/src/index.ts
packages/graphile-utils/src/makeProcessSchemaPlugin.ts

Fixes #353
Enables a way of processing the schema after it's built. Use cases:
- Printing the schema SDL to a file
- Uploading the schema SDL to a network service
- Checking the schema against your persisted queries
- Validating the schema against your custom logic
- Replacing the schema with a mocked version or a derivative version (e.g. stitching it with another schema)
- Integrating with third-party libraries such as graphql-middleware / graphql-shield which mutate the GraphQLSchema after it has been constructed

feat(utils): makeProcessSchemaPlugin

---

packages/graphile-utils/README.md
packages/graphile-utils/__tests__/makeWrapResolversPlugin.test.js
packages/graphile-utils/src/makeWrapResolversPlugin.ts

Enables you to wrap a class of resolvers rather than only ones that have a particular name.
```js
// Example: log before and after each mutation runs
module.exports = makeWrapResolversPlugin(
context => {
if (context.scope.isRootMutation) {
return { scope: context.scope };
}
return null;
},
({ scope }) => async (resolver, user, args, context, _resolveInfo) => {
console.log(`Mutation '${scope.fieldName}' starting with arguments:`, args);
const result = await resolver();
console.log(`Mutation '${scope.fieldName}' result:`, result);
return result;
}
);
```

feat(utils): enable wrapping resolvers matching a filter

---

packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/plugins/pgField.js
packages/postgraphile-core/__tests__/integration/__snapshots__/queries-jwt.test.js.snap
packages/postgraphile-core/__tests__/integration/queries-jwt.test.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/jwt.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

For anyone who has used bigint/numeric in their JWT types, this may cause issues as it changes the type from number to string; to fix this either update your code to handle arbitrary precision numbers, or change your database types to `int` / `float` for GraphQL compatibility.
Fixes https://github.com/graphile/postgraphile/issues/948

fix(jwt): handle bigint / numeric in JWTs

---

packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/postgraphile-core/__tests__/integration/queries-ranges.test.js
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

I've tried this by patching manually PgTypesPlugin.js in my node_modules and it seems to work fine
I tried to do this as a plugin as suggested but this was easier than rebuilding the whole Ranges types
I have not looked into the tests for this yet

fix(sql): tsrange, tstzrange, int8range and numrange now properly formatted

---

packages/graphile-build-pg/src/plugins/introspectionQuery.js

This simple PR updates the introspection query URL in introspectionQuery.js
The file was at some point inlined from explicitly loaded `introspection-query.sql` to `introspectionQuery.js` but the URL was never changed: the URL shows up when errors happen during introspections making it a bit confusing for the end users.

Update introspection query URL in introspectionQuery.js

---

packages/graphile-build/package.json
packages/graphile-build/src/makeNewBuild.js
yarn.lock

This PR updates graphile-build's lru-cache dependency to version 5.

chore(deps): upgrade lru-cache to version 5

---

packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/connections.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/inflect-core.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Fixes #404 
Requires `--subscriptions` to be enabled to force pulling down identifiers.
V5 will mandate that primary keys are selectable.

fix(nulls): fix null detection when requesting only nullable columns

---

packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/simple-collections.test.js

Fixes #397 
This is a bugfix, but people may be relying on this broken behaviour. If they are, they can opt out of this fix via `disableIssue397Fix` flag:
CLI: add to `.postgraphilerc.js`:
```js
module.exports = {
options: {
graphileBuildOptions: {
disableIssue397Fix: true
}
}
}
```
Library:
```js
app.use(postgraphile(DB, SCHEMAS, {
graphileBuildOptions: {
disableIssue397Fix: true
}
}));
```

 fix(simple): don't add edges to mutation payloads when simpleCollections only

---

packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.d.ts
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/introspectionQuery.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/queryFromResolveDataFactory.js

No need for user intervention, we auto-detect the permissions for each table.
Using this schema:
```sql
drop schema if exists perf cascade;
create schema perf;
set search_path to perf, public;
create table a (
id serial primary key,
name text not null,
foo text not null default 'slkdjfgp3ojtgo;irghpow jeg;sorijt ;w0ja;sdojrg 09a3[jw4 at;oidsfgj 90wej4t ;soejgr ajt34 ;oesjrg osdrg;sergeps89ngpse9trgpsdh9fg',
bar text not null default 'slkdjfgp3ojtgo;irghpow jeg;sorijt ;w0ja;sdojrg 09a3[jw4 at;oidsfgj 90wej4t ;soejgr ajt34 ;oesjrg osdrg;sergeps89ngpse9trgpsdh9fg',
baz text not null default 'slkdjfgp3ojtgo;irghpow jeg;sorijt ;w0ja;sdojrg 09a3[jw4 at;oidsfgj 90wej4t ;soejgr ajt34 ;oesjrg osdrg;sergeps89ngpse9trgpsdh9fg'
);
create table b (
id serial primary key,
a_id int not null references …
```

feat(perf): use more optimal query when no column-level select grants

---

packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js
packages/graphile-build-pg/src/queryFromResolveDataFactory.js

`totalCount` is now implemented via aggregates:
https://github.com/graphile/graphile-engine/blob/e08dbb34ee904cb54349c2152b7fe18ec3a4d1ca/packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js#L36-L41
Here's a plugin that adds the `sum` aggregate for numeric fields:
```js
module.exports = builder => {
// Add some inflection rules so users can rename things (this is optional!)
builder.hook('inflection', (inflection, build) => {
return build.extend(inflection, {
sumAggregate() {
return 'sum';
},
summableFieldEnum(table) {
return this.upperCamelCase(`${this._singularizedTableName(table)}-summable-field-enum`);
},
});
});
// Hook all connections to add the aggregate field
builder.hook('GraphQLObjectType:fields', (fields, build, context) => {
const {
pgSql: sql,
newWithHooks, …
```

feat(aggregates): add support for aggregates

---

packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
packages/graphile-utils/__tests__/utils-schema.sql
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

#413  introduced this feature, but it only worked when the connection and the parent type were from the same table (?!).

fix(utils): fix makeExtendSchemaPlugin @pgQuery directive

---

packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-utils/src/fieldHelpers.ts

Connections can be used for aggregates such as `totalCount`. If no nodes/cursors are requested then pulling down identifiers is unnecessary and leads to slower `totalCount` and unnecessary live fields.
This PR stops connection planners from pulling down identifiers and connection resolvers from registering live records, instead leaving that to the parts of the schema (`nodes` / `edges[].node` / `edges[].cursor`) that do require that functionality.
Fixes #428

fix(connection): don't query identifiers unless necessary

---

packages/graphile-build-pg/src/QueryBuilder.d.ts
packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgAllRows.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
packages/graphile-build-pg/src/plugins/PgRowNode.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/plugins/pgField.js
packages/graphile-build-pg/src/queryFromResolveDataFactory.js
packages/graphile-build/__tests__/Live.test.js
packages/graphile-build/src/Live.d.ts
packages/graphile-build/src/Live.js
packages/graphile-build/src/plugins/AddQueriesToSubscriptionsPlugin.js
packages/graphile-build/src/plugins/NodePlugin.js
packages/graphile-utils/src/fieldHelpers.ts
packages/graphile-utils/src/makeExtendSchemaPlugin.ts
packages/lds/__tests__/pg-logical-decoding.test.ts
packages/subscriptions-lds/src/PgLDSSourcePlugin.ts

Moves everything from `context` (which was a hack) to `rootValue` (which is our "payload" from the `subscribe` async iterator, so is officially under our control). 
If this is used outside of PostGraphile and you don't use a custom `liveSubscribe` function then the memory will increase unbounded; PostGraphile uses a custom subscribe function when live queries are enabled that triggers the release of each of the `rootValue`s that are generated.

fix(live): solve race conditions in live queries

---

packages/graphile-build-pg/src/queryFromResolveDataFactory.js

This is important for plugins that need to get access to certain special
table properties, such as `ctid`.
Once such example is https://github.com/mlipscombe/postgraphile-plugin-zombodb

feat(plugins): enable plugins to prevent using asterisk

---

.flowconfig
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/withPgClient.js

Fixes #427
- Reconnects if connection drops
- Re-runs introspection on reconnect in case anything changed when we were disconnected
- Reinstalls watch schema after reconnect in case the database was reset (as some people do in Docker)

fix(watch): rewrite schema watching; handle PostgreSQL server restart

---

packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/graphile-build-pg/src/plugins/introspectionQuery.js
packages/postgraphile-core/__tests__/integration/__snapshots__/queries-jwt.test.js.snap
packages/postgraphile-core/__tests__/integration/queries-jwt.test.js
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/inflect-core.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Enables the one-way relation required for `@foreignKey` to make sense on composite types that have no backing table/view/materialized view.

feat(smart-comments): @foreignKey smart comments on composite types

---

packages/subscriptions-lds/src/PgLDSSourcePlugin.ts

This caused some events for live queries not to come through when using the LD server in a standalone configuration.

fix(lds): correct the set of LDS announcement types handled

---

packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js

The "Failed to setup watch fixtures in Postgres database" has been corrected to suggest that the command line option is --owner-connection instead of --owner-connection-string.

Warning has typo in command line option suggestion

---

packages/graphile-build/package.json

I'm running into [implicit dependencies](https://pnpm.js.org/docs/en/faq.html#pnpm-does-not-work-with-your-project-here) when using pnpm, this should fix it. I'm using the version that `graphql` uses.

fix(deps): Add iterall to graphile-build dependencies for pnpm

---

packages/graphile-build/src/SchemaBuilder.d.ts
packages/graphile-build/src/SchemaBuilder.js
packages/graphile-build/src/makeNewBuild.js
packages/graphile-build/src/plugins/NodePlugin.js
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

Adds support for makeExtendSchemaPlugin defining unions and directives required for Apollo Federation support.
Does not have tests.
HIGHLY EXPERIMENTAL.
_Note: don't get excited, this does not improve support for unions, it just allows you to express them via SDL rather than having to write them out manually. The same "root and leaves only" union rule applies to unions - you can't have unions in the middle of the tree because our query planner still doesn't understand them in that position._

feat(utils): make extend schema plugin more powerful

---

packages/graphile-utils/package.json

I'm getting a warning at the moment when installing. Are `peerDependencies` skipped on purpose?

chore(deps): Update peerDependencies of graphile-utils

---

packages/graphile-build-pg/src/inflections.js
packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-build-pg/src/plugins/addStartEndCursor.js
packages/graphile-build-pg/src/plugins/makeProcField.js
packages/graphile-build-pg/src/utils.js
packages/graphile-build/src/makeNewBuild.js
packages/postgraphile-core/__tests__/integration/queries-jwt.test.js

The [object spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals) is shorter and clearer to read than `Object.assign()`. This pull request changes several usages of `Object.assign()` to the object spread operator.
Note that there are several other usages of `Object.assign()` in the codebase that I did _not_ change in this pull request. It looks like the code is sometimes doing some fancy stuff with object prototypes, and I didn't want to risk accidentally breaking something. This pull request only changes code that is clearly expecting a plain object literal out of the result of `Object.assign()`, which makes them safe to rewrite using the object spread operator.

Replace Object.assign() with object spread operator

---

packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
packages/graphile-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js
packages/graphile-build/src/plugins/ClientMutationIdDescriptionPlugin.js

Follow up to #488. `name` is not a field on `GraphQLFieldConfig` ([see the docs for `graphql-js`](https://graphql.org/graphql-js/type/#graphqlobjecttype)) so any reference to `field.name` returns `undefined`. Instead, we should use the `fieldName` from the `scope` object.

Get fieldName from scope, instead of field.name

---

packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.d.ts
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
packages/postgraphile-core/__tests__/fixtures/queries/large_bigint.issue491.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Changing a primary key column from `int` to `bigint` does not change the nodeId (deliberately), but all nodeIds over 9 quadrillion (2^53 - 1) have now changed.
This also changes the representation for node identifiers for numeric/decimal (arbitrary precision) numbers and money to use numeric strings to maintain precision.
This is a fix to behaviour that was previously broken; it should only affect you if the full range of your primary key fields cannot be safely represented in a JavaScript number (e.g. bigint > 9 quadrillion, numeric/decimal arbitrary precision numbers, etc) or if you're using the "money" type in a primary key.
Fixes #491

fix(nodeId): fix object IDs for arbitrary precision numbers and ints > 9 quadrillion

---

packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
packages/graphile-build/src/makeNewBuild.js

Shouldn't break existing schemas because it only fixes things that are invalid.
Fixes https://github.com/graphile/postgraphile/issues/1119

fix(inflectors): names that begin with a digit are prefixed with underscore

---

packages/postgraphile-core/__tests__/unit/__snapshots__/read-cache.test.js.snap
packages/postgraphile-core/__tests__/unit/read-cache.test.js
packages/postgraphile-core/src/index.ts

This is still a Work in progress, I'm opening the PR to discuss the changes.
This PR add unit tests for `readCache` option in `getPostGraphileBuilder`. See test suite for details
There are no changes to `src` files (except exporting `getPostGraphileBuilder` function) , so it should be safe to merge once accepted.

Unit Test read cache

---

packages/graphile-build-pg/src/plugins/introspectionQuery.js

closes https://github.com/graphile/postgraphile/issues/1138

fix(introspection): corrected bitmasks for mutability checks

---

packages/graphile-build-pg/src/queryFromResolveDataFactory.js

When using the cursor for pagination (```before``` and ```after```) Graphile requires that the ```orderBy``` clause must be composed by unique value, either referring the table PK or mixing values that returns a unique result.
Currently when the query fails due to that error the message returned is ```Cannot use cursors without orderBy```, which is misleading, because there might be an ```orderBy``` clause passed, but it's not correctly assigned.
This PR uses a validation that already exists in the codebase and throws an error message based on the flag returned from it.

feat(query): improve unique orderBy error message

---

packages/postgraphile-core/__tests__/unit/__snapshots__/read-cache.test.js.snap
packages/postgraphile-core/__tests__/unit/read-cache.test.js
packages/postgraphile-core/src/index.ts

*This is still a Work In Progress, do not merge :)*
This PR allows passing a `readCache object` to `getPostGraphileBuilder`. The functionality is backwards compatible, passing a `readCache` string with a path to a file will still work on the same way.

feat: allow passing readCache as an object

---

packages/graphile-utils/src/index.ts
packages/graphile-utils/src/makeAddPgTableConditionPlugin.ts
packages/graphile-utils/src/makeAddPgTableOrderByPlugin.ts

Thanks to http://sprout.io for allowing me to open source these plugin generators :pray: 
Since these plugins have no tests, they're currently marked as experimental.

feat(utils): Add PG plugin generators for conditions/orderBy

---

package.json
packages/graphile-utils/package.json
packages/lru/package.json
packages/pg-sql2/package.json
packages/postgraphile-core/package.json
yarn.lock

We use root-level `eslint` only, so no need for per-package prettier.

chore(deps): remove prettier from subpackages

---

packages/pg-sql2/package.json
yarn.lock

This allows us to drop Babel 6 from `yarn.lock`!

markdown-doctest 1.0.0

---

yarn.lock

I just tried installing `yarn install` on the repo, and unexpectedly found that it changed `yarn.lock`. Must be changes from https://github.com/graphile/graphile-engine/pull/538 that somehow didn't get committed? Weird.

chore(deps): clean up yarn.lock

---

packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.d.ts
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/introspectionQuery.js

The PgIndex type currently do not have a way to know if the index is a partial index or not, making it hard to decide and use the index inside plugin. The `indpred` field that existed in postgresql index since 7.1+  shows the predicate of the index, describe the "where clause" of the index. If it is not null, it is an expression of "what part of all records should be in this index". If this field is NULL, it means the index is not partial. 
Also added field to Flow type and ts type.

feat(pg): add partial index detection to introspection

---

package.json
yarn.lock

Looks like we're still marking `babel-core` as a devDependency (as opposed to `@babel/core`). Since we're on Babel 7 everywhere, I don't think we need `babel-core` anymore.

chore(deps): remove babel core bridge

---

packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

We had already chatted about this - this PR allows for scalars to be added as subqueries using the `@pgQuery` directive with the `fragment` argument.
If this is merged, it would be great if you could mention my employer [Mayflower](https://mayflower.de/) in the release notes, as this PR was done on company time. But if this something you don't do, thats fine, too :smiley:

feat(utils): @pgQuery support for scalars

---

packages/graphile-build-pg/package.json
packages/graphile-build/package.json
packages/graphile-utils/package.json
packages/jest-serializer-graphql-schema/package.json
packages/pg-pubsub/package.json
packages/postgraphile-core/package.json

- Fixed `yarn watch`
- Fixed new peerdep warning
- Added devDependencies on the new module

chore: fix development flow for jest-serializer-graphql-schema

---

packages/graphile-build-pg/src/QueryBuilder.d.ts
packages/graphile-build-pg/src/QueryBuilder.js
packages/postgraphile-core/__tests__/fixtures/queries/named_query_builder.toys.graphql
packages/postgraphile-core/__tests__/integration/ToyCategoriesPlugin.js
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/queries.test.js
packages/postgraphile-core/__tests__/kitchen-sink-data.sql
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

This adds three new public methods to the `QueryBuilder` class: `buildChild`, `buildNamedChildFrom`, and `getNamedChild`. These new methods will enable new capabilities for PostGraphile plugins. @benjie and I discussed this via Discord a few days ago, so I know he approves of these new methods.
I do have a few qustions:
* Should we also add a `buildNamedChild` method, which is like `buildNamedChildFrom` but does not call the `select`, `from`, or `lock` methods? It seems like an obvious extension of this API, but I'm not sure if it's actually useful/necessary. It might be better to wait until we find a use-case before building it.
* Should I add automated tests for this change? I don't see any automated tests for the `QueryBuilder` class at all.

feat(QueryBuilder): new methods for managing QB children

---

packages/graphile-build-pg/src/QueryBuilder.d.ts
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

Two tweaks:
- `ExtensionDefinition.resolvers` should be optional, as seen [in the docs here](https://www.graphile.org/postgraphile/make-extend-schema-plugin/#using-the-pgquery-directive-for-non-root-queries-and-better-performance), and verified that this change is OK to make [at the call site here](https://github.com/graphile/graphile-engine/blob/1689f6691a0716d41d256de3499c9da40407348f/packages/graphile-utils/src/makeExtendSchemaPlugin.ts#L109) as there is a default empty object
- `QueryBuidler.orderBy` should have `ascending` and `nullsFirst` as optional, as seen also [in the docs here](https://www.graphile.org/postgraphile/make-extend-schema-plugin/#using-the-pgquery-directive-for-non-root-queries-and-better-performance), and verified that this change is OK to make [at the call site …

fix(types): minor TypeScript fixes

---

packages/postgraphile-core/src/index.ts

Not much of a change, but prerequisite for https://github.com/graphile/postgraphile/pull/1167 to typecheck. Also useful in general :-)

Use jwt.Secret type in PostgraphileCoreOptions

---

packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/queryFromResolveDataFactory.js
packages/postgraphile-core/__tests__/fixtures/queries/procedure-query.graphql
packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/inflect-core.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simplePrint.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
packages/postgraphile-core/__tests__/kitchen-sink-schema.sql

Fixes https://github.com/graphile/postgraphile/issues/1171
`useAsterisk` runs certain code in a subquery as an optimisation; so:
```sql
select /* COMPLEX STUFF */
from /* EXPENSIVE THING */
limit 2 offset 2
```
becomes
```sql
select /* COMPLEX STUFF */
from (
select *
from /* EXPENSIVE THING */
limit 2 offset 2
) as __alias__
```
This is great because it means that PostgreSQL can process the rows in the subquery more efficiently, and doesn't have to execute the "COMPLEX STUFF" until it's thrown most of the rows from "EXPENSIVE THING" away. Less computation = faster queries (even though they're a little more complex).
HOWEVER because we've moved the LIMIT/OFFSET to the subquery, any calls to `row_number()` are now different than they were before because they no longer include the OFFSET. …

fix(pagination): fix bug in cursor pagination for PL/pgSQL SETOF functions

---

packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
packages/graphile-utils/src/makeExtendSchemaPlugin.ts

E.g. if we need to enable a subquery that references the parent query builder's alias.
```graphql
foo: ItemConnection @pgQuery(
source: ${embed(
({ parentQueryBuilder }) => sql.fragment`(
select items.*
from mindtree_public.items
inner join lateral unnest(${parentQueryBuilder.getTableAlias()}."starredTopicIds") with ordinality as star(id, idx) on (star.id = items.id)
where items.type = 'TOPIC'
order by idx asc
)`
)}
withQueryBuilder: ${...}
)
```
NOTE: we should also allow blocking the default value for the `orderBy` argument which is added automatically (I think?) - e.g. in this case it's important the default order is `NATURAL` since the result set is already ordered (but the order value does not leak).

feat(utils): `@pgQuery.source` can be function

---

packages/graphile-utils/src/makePgSmartTagsPlugin.ts

- deprecates `columns` shortcut
- adds `attribute` shortcut (renamed from `columns` for consistency)
- adds `constraint` shortcut for table constraints
- improves error messages
- fixes a bug in warning message that cased error to throw

feat(tags): improve JSON format for Smart Tags

---

packages/graphile-utils/src/makeAddPgTableConditionPlugin.ts

We need to allow `{allFoos(condition:{myCustomCondition: null}){...}}` to trigger the condition callback (and it's up to that how to handle the null); however if the condition was not specified (e.g. `{allFoos(condition:{}){...}}`) then the callback should not be consulted.
This is technically a breaking change, but this plugin is still marked as experimental, so it only counts as a fix in this case.

fix(utils): only apply condition when specified

---

.eslintignore
.eslintrc.js
.gitignore
.travis.yml
package.json
packages/graphile-build-pg/src/QueryBuilder.js
packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
packages/graphile-utils/__tests__/makeProcessSchemaPlugin.test.js
packages/jest-serializer-graphql-schema/README.md
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/omit-rename.omitstuff.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simplePrint.test.js.snap
packages/postgraphile-core/__tests__/integration/schema/omit-rename.omitstuff.test.js
packages/postgraphile-core/__tests__/integration/schema/simplePrint.test.js
packages/postgraphile-core/src/index.ts
release
yarn.lock

`master` now represents v5 (including the TypeScript refactoring), so I've back-ported some of the fixes from that branch into the v4 branch.

feat: selectively back-port fixes from master

---

packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
packages/graphile-build-pg/src/plugins/introspectionQuery.js

This fix is to make the introspection query not iterate over every role in the database on startup when `--no-ignore-rbac` is not present. (We are the crazy people with 4000+ roles and the 16 minute start times)
We patched our local copy of Postgraphile by just removing the `union all` below, but we wanted to make sure this didn't get broken by future versions and wanted to contribute back.
I'm new to typescript and I think I followed everything correctly.  Everything built and appeared to start up correctly with and without the `--no-ignore-rbac` parameter.

fix(introspection): don't query roles when ignoring RBAC

---

.travis.yml
packages/pg-pubsub/src/PgSubscriptionResolverPlugin.ts

Extends the `@pgSubscription` directive with an `initialEvent` argument allowing you to guarantee data freshness by emitting an event which triggers the related resolver as soon as the user subscribes.
```js
// FileSubscriptionPlugin.js
import { makeExtendSchemaPlugin, gql, embed } from 'graphile-utils';
function buildTopic(args) {
return `fileChanged:${args.id}`;
}
function buildInitialEvent(args) {
// the `topic` value will be injected in the returning event
return { subject: args.id };
}
export const FileSubscriptionPlugin = makeExtendSchemaPlugin(({ pgSql: sql }) => ({
typeDefs: gql`
type FileChangedPayload {
event: String!
file: File!
}
extend type Subscription {
fileChanged(id: UUID!): FileChangedPayload!
@pgSubscription(
topic: ${embed(buildTopic)}
initialEvent: …
```

feat(subscriptions): @pgSubscription now supports initial events
