- packages/graphql-build-pg/src/plugins/PgAllRows.js
- packages/graphql-build-pg/src/plugins/PgBackwardRelationPlugin.js
- packages/graphql-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphql-build-pg/src/plugins/PgComputedColumnsPlugin.js
- packages/graphql-build-pg/src/plugins/PgConnectionArgCondition.js
- packages/graphql-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphql-build-pg/src/plugins/PgConnectionTotalCount.js
- packages/graphql-build-pg/src/plugins/PgForwardRelationPlugin.js
- packages/graphql-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphql-build-pg/src/plugins/PgJWTPlugin.js
- packages/graphql-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/graphql-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
- packages/graphql-build-pg/src/plugins/PgMutationProceduresPlugin.js
- packages/graphql-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
- packages/graphql-build-pg/src/plugins/PgQueryProceduresPlugin.js
- packages/graphql-build-pg/src/plugins/PgRowByUniqueConstraint.js
- packages/graphql-build-pg/src/plugins/PgRowNode.js
- packages/graphql-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
- packages/graphql-build-pg/src/plugins/PgTablesPlugin.js
- packages/graphql-build-pg/src/plugins/makeProcField.js
- packages/graphql-build/README.md
- packages/graphql-build/__tests__/fieldData.test.js
- packages/graphql-build/__tests__/watch.test.js
- packages/graphql-build/src/SchemaBuilder.js
- packages/graphql-build/src/makeNewBuild.js
- packages/graphql-build/src/plugins/MutationPlugin.js
- packages/graphql-build/src/plugins/NodePlugin.js
- packages/graphql-build/src/plugins/QueryPlugin.js
- packages/graphql-build/src/plugins/StandardTypesPlugin.js
> Rename a few things to make more sense

- .babelrc
- .flowconfig
- package.json
- packages/graphql-build-pg/index.js
- packages/graphql-build/index.js
- packages/graphql-parse-resolve-info/index.js
- packages/pg-sql2/index.js
- packages/pg-sql2/src/index.js
- packages/postgraphql-build/index.js
- scripts/ci
- yarn.lock
This adds flow tooling, and fully flows pg-sql2.
> Add Flow tooling

- .babelrc
- .eslintignore
- .eslintrc.js
- .gitignore
- README.md
- package.json
- packages/graphql-build-pg/.gitignore
- packages/graphql-build-pg/index.js
- packages/graphql-build-pg/package.json
- packages/graphql-build/.gitignore
- packages/graphql-build/index.js
- packages/graphql-build/package.json
- packages/graphql-parse-resolve-info/.gitignore
- packages/graphql-parse-resolve-info/index.js
- packages/graphql-parse-resolve-info/package.json
- packages/graphql-parse-resolve-info/src/index.js
- packages/postgraphql-build/.gitignore
- packages/postgraphql-build/index.js
- packages/postgraphql-build/package.json
- scripts/ci
- yarn.lock
Allows us to use fancy features from ES2017+ and also prettier Flow.
> chore: switch over to building everything

- packages/graphql-build/__tests__/__snapshots__/enum.test.js.snap
- packages/graphql-build/__tests__/__snapshots__/fieldData.test.js.snap
- packages/graphql-build/__tests__/__snapshots__/watch.test.js.snap
- packages/graphql-build/src/plugins/NodePlugin.js
Should have been `id` all along, not `nodeId`!
> fix(node): change nodeIdFieldName to 'id'

- packages/graphile-build-pg/src/plugins/viaTemporaryTable.js
See explanation in the code. Possibly the longest comment I've written recently!
> fix(mutations): remove temp tables due to privilege requirements

- packages/graphile-build-pg/src/plugins/PgRowNode.js
- packages/graphile-build/src/SchemaBuilder.js
- packages/graphile-build/src/makeNewBuild.js
- packages/graphile-build/src/plugins/NodePlugin.js
No need for two functions that do similar things.
> chore(debt): remove generateDataForType

- packages/graphile-build-pg/src/QueryBuilder.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
- packages/graphile-build-pg/src/queryFromResolveData.js
- packages/postgraphile-core/__tests__/fixtures/queries/procedure-query.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
> feat(pagination): allow using cursors with orderBy=NATURAL

- packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries-jwt.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/integration/queries-jwt.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(jwt): return null on null JWT

- packages/graphile-build-pg/src/QueryBuilder.js
This PR ensures that any user-defined column aliases match a carefully crafted RegExp. It should never be possible for this error to throw since GraphQL does this validation for us already; but it seems prudent to be cautious!
Inspired by https://github.com/brianc/node-postgres/issues/1408
> fix(security): double-ensure safety of column aliases

- packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Validates the fix in #49
Confirms it fixes https://github.com/postgraphql/postgraphql/issues/555
> chore(test): GUID test case

- packages/graphile-build-pg/src/index.js
> feat: export case utils

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
> Fix UUID type with `pgExtendedTypes`

- packages/graphile-build-pg/res/introspection-query.sql
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationProceduresPlugin.js
- packages/graphile-build-pg/src/plugins/PgOrderAllColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js
- packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
- packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
> fix(types): allow JWT from private schema; pass non-null schema name to inflectors

- packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-create.graphql
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-update.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fixes #71 
Fixes postgraphql/postgraphql#584
cc @EyMaddis
> fix(mutations): setting null on create for nullable column with non-null default

- packages/graphile-build-pg/src/inflections.js
- packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
> add foreign table to manyRelationByKeys call

- README.md
> link to docker env wiki page in readme

- packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
- packages/postgraphile-core/__tests__/fixtures/queries/connections.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
> Restore filtering for null to default condition plugin

- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
> fix(columns): don't let columns overwrite each-other

- packages/graphile-build-pg/src/queryFromResolveData.js
> fix(cursors): only use cursor when order is unique

- README.md
- packages/postgraphile-core/README.md
> docs: add PostGraphile links to READMEs

- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> correctly detect non nullable domain

- packages/graphile-build-pg/package.json
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- yarn.lock
> fix(dependencies): Solve missing dependency

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-create.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(types): Prevent numeric overflow for arbitrary-precision types

- packages/graphile-build-pg/src/plugins/PgMutationProceduresPlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(custom-mutations): Allow mutation procedures to accept table args

- packages/graphile-build-pg/src/index.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderByDefaultValue.js
> Refactor defaultValue from PgConnectionArgOrderBy as a separate plugin

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
Fixes #136 
⚠️  Breaking change ⚠️  (Changes a type name.)
> fix(types): use named BigFloat type over GraphQLString

- packages/graphile-build-pg/src/QueryBuilder.js
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphile-build-pg/src/utils.js
- packages/postgraphile-core/__tests__/fixtures/queries/procedure-computed-fields.graphql
- packages/postgraphile-core/__tests__/fixtures/queries/types.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fixes #137
Would be nice to come up with a more efficient way of doing this in future.
> fix(composite-types): Fix null composite column issue

- packages/graphile-build-pg/src/QueryBuilder.js
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
- packages/graphile-build-pg/src/utils.js
- packages/graphile-build/src/SchemaBuilder.js
- packages/graphile-build/src/makeNewBuild.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-delete.graphql
- packages/postgraphile-core/__tests__/fixtures/queries/procedure-computed-fields.graphql
- packages/postgraphile-core/__tests__/fixtures/queries/types.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(delete): always populate deleted nodeId

- packages/graphile-build-pg/res/introspection-query.sql
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-create.graphql
- packages/postgraphile-core/__tests__/fixtures/queries/types.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> feat(types): add support for 'point' type

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/fixtures/queries/procedure-query.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fixes https://github.com/postgraphql/postgraphql/issues/678
> fix(precision): Fix bigint/bigfloat precision loss

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
Fixes https://github.com/graphile/graphile-build/issues/45
You can use `pgThrowOnMissingSchema` if you want, but it's undocumented and may be broken in future releases - don't rely on it.
> feat(errors): Warn when a DB schema is missing

- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
> fix(schema): remove incorrect 'pagination' comments

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphile-build-pg/src/withPgClient.js
> feat(pg): duck-type PG to prevent 'provide valid PG client' error

- packages/graphile-build-pg/package.json
- packages/graphile-build-pg/src/GraphQLJSON.js
- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema.test.js
- packages/postgraphile-core/src/index.js
- yarn.lock
> feat(compat): enable lower case Json/Uuid like v3

- README.md
- packages/graphile-build-pg/README.md
- packages/graphile-build-pg/res/introspection-query.sql
- packages/graphile-build-pg/res/watch-fixtures.sql
- packages/graphile-build-pg/src/index.js
- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
- packages/graphile-build-pg/src/plugins/PgNodeAliasPostGraphile.js
- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/graphile-build/README.md
- packages/graphql-parse-resolve-info/src/index.js
- packages/postgraphile-core/README.md
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries-jwt.test.js.snap
- packages/postgraphile-core/__tests__/integration/mutations.test.js
- packages/postgraphile-core/__tests__/integration/queries-jwt.test.js
- packages/postgraphile-core/__tests__/integration/queries.test.js
- packages/postgraphile-core/__tests__/integration/schema.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
For consistency along with the beta release
> chore(rename): rename a bunch of postgraphql -> postgraphile

- packages/graphile-build-pg/src/QueryBuilder.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries-jwt.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/integration/queries-jwt.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fix https://github.com/graphile/postgraphile/issues/708
I don't think this will change any existing functionality.
> fix(sql): remove unnecessary row expansion

- packages/graphql-parse-resolve-info/__tests__/__snapshots__/test.test.js.snap
- packages/graphql-parse-resolve-info/__tests__/test.test.js
- packages/graphql-parse-resolve-info/src/index.js
Fixes the issue raised in this comment: https://github.com/graphile/postgraphile/issues/549#issuecomment-375471896
> fix(directives): Omit skipped fields from execution plan

- packages/graphile-build-pg/src/GraphQLJSON.js
- packages/postgraphile-core/__tests__/fixtures/queries/dynamic-json.condition-json-field-variable.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/schema.test.js.snap
- packages/postgraphile-core/__tests__/integration/queries.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fixes https://github.com/graphile-contrib/postgraphile-plugin-connection-filter/issues/33
> fix(dynamic-json): variables in dynamic JSON subfields now supported

- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/fixtures/queries/connections-totalCount.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
Fixes https://github.com/graphile/postgraphile/issues/762
> fix(procs): fix querying only `totalCount` on procedure connections

- packages/postgraphile-core/__tests__/fixtures/queries/simple-procedure-computed-fields.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
> Simple collections - more tests

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-create.graphql
- packages/postgraphile-core/__tests__/fixtures/queries/connections.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/integration/mutations.test.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
Fixes #4 
Fixes graphile/postgraphile#311
Fixes graphile/postgraphile#571
> feat(hstore): add support for the hstore type

- packages/postgraphile-core/src/index.js
> fix(plugins): detect null plugins

- packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> feat(smart-comments): can edit description of relation fields

- packages/graphile-build-pg/src/plugins/PgAllRows.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
>  feat(smart-comments): can override pgViewUniqueKey for a view

- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/mutation-update.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
- packages/postgraphile-core/__tests__/kitchen-sink-data.sql
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
(Still requires unique keys though!)
This turned out to be a premature return bug. Switching to an if statement instead fixed it 👍 
Fixes https://github.com/graphile/postgraphile/issues/735
> fix(mutations): add update and delete mutations for tables lacking primary key

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
type name was not shown correctly
> fix error message for internal error "should not attempt to tweak an array"

- packages/graphile-build-pg/res/introspection-query.sql
> fix(ignore-extensions): add pg_depend.classid clause to introspection

- package.json
- packages/graphile-build-pg/package.json
- packages/graphile-build/package.json
- packages/graphile-utils/package.json
- packages/graphql-parse-resolve-info/package.json
- packages/postgraphile-core/package.json
- yarn.lock
And build yarn.lock from scratch.
> chore: update dependencies to use ^ or similar

- packages/graphile-utils/README.md
Just the makeExtendSchemaPlugin bit.. not sure why it's flagging L107
> docs: fix typo

- packages/graphile-build-pg/src/plugins/PgNodeAliasPostGraphile.js
- packages/graphile-build-pg/src/plugins/PgRowNode.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/skipNodePlugin.test.js
> feat: make skipping NodePlugin easier

- packages/graphile-build/src/SchemaBuilder.d.ts
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/invalidSkipPlugins.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/invalidSkipPlugins.test.js
- packages/postgraphile-core/src/index.ts
> feat: detect invalid skipPlugins option

- packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/extend-errors.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/core.js
- packages/postgraphile-core/__tests__/integration/schema/function-clash.test.js
Fixes #313 
This was already working, but I've enhanced the error message and added a test to ensure it will always warn the user.
> chore: add test for create mutation / function clash

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphile-build-pg/src/plugins/introspectionQuery.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/legacyFunctionsOnly.test.js
- packages/postgraphile-core/src/index.ts
This is an opt-out option for the functionality introduced in #296.
> feat: `pgLegacyFunctionsOnly` option

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
It's recommended to run PostGraphile using non-superuser privileges; however this prevents installing the watch fixtures. You can install them yourself (see below) but then you still get a warning.
This PR enables PostGraphile to skip attempting to install the fixtures, instead assuming that you've handled this elsewhere in your code. The easiest way to test this is to add this to your `.postgraphilerc.js` file:
```js
module.exports = {
options: {
graphileBuildOptions: {
pgSkipInstallingWatchFixtures: true,
}
}
};
```
---
To install the watch fixtures yourself, do something like this:
```js
const readFile = require("util").promisify(require("fs").readFile);
function findWatchFixtures() {
try {
return require.resolve("postgraphile/node_modules/graphile-build-pg/res/watch-fixtures.sql");
} …
```
> feat(watch): option to skip installing watch fixtures

- packages/graphql-parse-resolve-info/src/index.ts
> fix(typescript): ignore fieldASTs warning

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.d.ts
- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
This adds types related to https://github.com/graphile/graphile-engine/pull/335
> chore: add types for introspected index column properties

- packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
> fix: make scalar function connection nodes nullable

- packages/graphile-build-pg/src/plugins/PgConnectionArgFirstLastBeforeAfter.js
- packages/postgraphile-core/__tests__/fixtures/queries/connections-blankcursor.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/queries.test.js.snap
> fix(cursors): fix bad cursor error

- packages/postgraphile-core/__tests__/fixtures/mutations/inheritence.createUserFile.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/mutations.test.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.inheritence.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/defaultOptions.inheritence.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
This adds tests for the issue raised in https://github.com/graphile/postgraphile/issues/930
However the tests pass so no further action is necessary at this time.
> test(inheritance): add simple table inheritance test

- packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
Fixes https://github.com/graphile/postgraphile/issues/942
> feat(indexes): always warn on FK skip due to no index

- packages/graphile-build-pg/src/plugins/introspectionQuery.js
- packages/graphile-build/src/SchemaBuilder.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(compatibility): don't fail at introspection when intarray extension is installed

- packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
Surprised no-one spotted this!
> fix(typo): pgInflection -> pgIntrospection

- packages/graphile-build-pg/__tests__/tags.test.js
- packages/graphile-build-pg/src/utils.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> fix(windows): add support for Windows CRLF in smart comments

- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphile-build-pg/src/plugins/PgOrderComputedColumnsPlugin.js
> fix(regression): restore old orderBy call signature

- packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
- packages/postgraphile-core/__tests__/fixtures/mutations/procedure-mutation.graphql
- packages/postgraphile-core/__tests__/integration/__snapshots__/mutations.test.js.snap
> fix(procs): fix relation errors in custom mutations when returning null

- .gitignore
- packages/graphile-build-pg/src/plugins/PgAllRows.js
- packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
- packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/simple-collections.test.js
- packages/postgraphile-core/__tests__/kitchen-sink-schema.sql
> feat(smart-comments): simpleCollections smart comment

- packages/graphile-build-pg/src/plugins/PgAllRows.js
- packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
- packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
- packages/graphile-build-pg/src/plugins/PgRowNode.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/graphile-build/__tests__/fieldData.test.js
- packages/lds/__tests__/pg-logical-decoding.test.ts
> fix(args): allow makeWrapResolversPlugin to override args

- packages/graphile-build-pg/src/plugins/PgConnectionTotalCount.js
- packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
- packages/pg-pubsub/__tests__/__snapshots__/subs.test.ts.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.inheritence.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/inflect-core.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/jwt.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/omit-rename.omitcolumns.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/omit-rename.omitstuff.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/omit-rename.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pg10.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/smart_comment_relations.test.js.snap
Fixes https://github.com/graphile/postgraphile/issues/959
> fix(nulls): totalCount shouldn't be nullable

- packages/graphile-build-pg/src/QueryBuilder.d.ts
- packages/graphile-build/src/SchemaBuilder.js
- packages/graphile-build/src/makeNewBuild.js
- packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
- packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
- packages/graphile-utils/__tests__/makeWrapResolversPlugin-pg.test.js
- packages/graphile-utils/__tests__/utils-schema.sql
- packages/graphile-utils/src/fieldHelpers.ts
- packages/graphile-utils/src/makeExtendSchemaPlugin.ts
Example plugin:
```js
const { makeExtendSchemaPlugin, gql, embed } = require('graphile-utils');
module.exports = makeExtendSchemaPlugin(build => {
const { pgSql: sql } = build;
return {
typeDefs: gql`
extend type Query {
myCustomConnection: UsersConnection
}
`,
resolvers: {
Query: {
myCustomConnection(_parent, args, context, resolveInfo) {
return resolveInfo.graphile.selectGraphQLResultFromTable(
sql.fragment`c.person`
// Or, e.g.:
// sql.fragment`(select person.* from c.person where id % 2 = 1)`
);
},
},
},
};
});
```
Example plugin for non-root queries:
```js
const { makeExtendSchemaPlugin, gql, embed } = require('graphile-utils');
module.exports = makeExtendSchemaPlugin(build => {
const { pgSql: sql } = build;
return {
typeDefs: gql`
extend type User {
myCustomConnection: …
```
> feat(utils): support connections in makeExtendSchemaPlugin

- packages/graphile-build-pg/src/index.d.ts
- packages/graphile-build/src/index.d.ts
- packages/pg-pubsub/src/PgGenericSubscriptionPlugin.ts
- packages/pg-pubsub/src/PgSubscriptionResolverPlugin.ts
> fix(ts): replace 'export *' with explicit exports to allow declaration merging

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
Only have one client attempt re-connect at a time.
> fix(pg): handle more errors on Postgres restart

- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
> fix(graphql): --no-setof-functions-contain-nulls now applies to simple collections too

- package.json
- packages/pg-pubsub/package.json
- yarn.lock
> chore(deps): upgrade postgraphile dev-dep

- packages/graphile-utils/__tests__/ExtendSchemaPlugin.test.js
- packages/graphile-utils/src/gql.ts
> feat(gql): enable composing multiple gql tags

- packages/graphile-build-pg/src/plugins/PgTypesPlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/defaultOptions.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/disabledTagsNoLegacyRelations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/function-clash.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/inflect-core.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/jwt.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyFunctionsOnly.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/legacyRelationsOnlyLegacyJsonNoTags.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/noDefaultMutations.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/pgColumnFilter.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/rbac.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/relay1.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simple-collections.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/skipNodePlugin.test.js.snap
Not sure if this is where this description originates.
> Fix typo in big-int definition.

- .eslintignore
- babel.config.js
- packages/graphile-build-pg/package.json
- packages/graphile-build-pg/src/QueryBuilder.js
- packages/graphile-build-pg/src/pgPrepareAndRun.js
- packages/graphile-build-pg/src/plugins/PgAllRows.js
- packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphile-build-pg/src/plugins/PgRowByUniqueConstraint.js
- packages/graphile-build-pg/src/plugins/PgRowNode.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/graphile-build-pg/src/queryFromResolveDataFactory.js
- packages/graphile-build/src/makeNewBuild.js
- packages/graphql-parse-resolve-info/.gitignore
- packages/graphql-parse-resolve-info/index.js
- packages/graphql-parse-resolve-info/package.json
- packages/graphql-parse-resolve-info/src/index.ts
- tsconfig.json
- tslint.json
- yarn.lock
- use prepared statements
- use faster loops
- precompute more
- upgrade pg-sql2 for faster identifier escaping
- branch smartly
> perf: a number of performance optimisations

- packages/graphile-build-pg/src/plugins/PgJWTPlugin.js
- packages/postgraphile-core/src/index.ts
I don't know how to build those packages, but modification of the compiled files in the PostGraphile app makes what it should. So I just copied changes to the original package files and PR'ing them.
> Add support for jsonwebtoken.sign options

- packages/graphile-build-pg/src/plugins/PgMutationPayloadEdgePlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/simplePrint.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/simplePrint.test.js
Fixes https://github.com/graphile/postgraphile/issues/1123
Fixes https://github.com/graphile/postgraphile/issues/1108
> fix(schema): set list default value for edge on mutation payload

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/indexes.test.js.snap
> fix(ignoreIndexes): mark fake constraints as indexed

- packages/pg-pubsub/src/index.ts
> fix(pubsub): use perpetual exponential back-off

- packages/graphile-build/src/plugins/NodePlugin.js
> fix(nodeIds): warn if two types try and register the same alias

- packages/graphile-build-pg/src/queryFromResolveDataFactory.js
- yarn.lock
> fix(cursors): better cursor validation

- README.md
- packages/pg-pubsub/__tests__/subs.test.ts
See https://github.com/graphile/postgraphile/issues/1136, https://github.com/graphile/postgraphile/pull/1145
> docs(CONTRIBUTING): standardise database setup instructions

- packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgComputedColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgCondition.js
- packages/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js
- packages/graphile-build-pg/src/plugins/PgForwardRelationPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationCreatePlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationProceduresPlugin.js
- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
- packages/graphile-build-pg/src/plugins/PgOrderAllColumnsPlugin.js
- packages/graphile-build-pg/src/plugins/PgQueryProceduresPlugin.js
- packages/graphile-build-pg/src/plugins/PgRecordFunctionConnectionPlugin.js
- packages/graphile-build-pg/src/plugins/PgRecordReturnTypesPlugin.js
- packages/graphile-build-pg/src/plugins/PgRowNode.js
- packages/graphile-build-pg/src/plugins/PgScalarFunctionConnectionPlugin.js
- packages/graphile-build-pg/src/plugins/PgTablesPlugin.js
- packages/graphile-build-pg/src/plugins/makeProcField.js
- packages/postgraphile-core/__tests__/integration/__snapshots__/extend-errors.test.js.snap
> chore(errors): add 'a Smart Comment' to relevant error messages

- packages/graphile-build-pg/src/plugins/PgMutationUpdateDeletePlugin.js
Fixes https://github.com/graphile/postgraphile/issues/1154
> fix(omit): if you omit update on all columns don't throw

- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphile-build/src/SchemaBuilder.js
> fix(watch): don't built schema twice in watch mode

- README.md
- packages/graphile-build-pg/README.md
- packages/graphile-build/README.md
- packages/graphile-utils/README.md
- packages/graphql-parse-resolve-info/README.md
- packages/lds/README.md
- packages/pg-pubsub/README.md
- packages/pg-sql2/README.md
- packages/postgraphile-core/README.md
- packages/subscriptions-lds/README.md
- scripts/sponsors
Thank you to all our Featured Sponsors, past and present, for supporting our work 🤩
> sponsorship: update READMEs

- packages/graphile-build/src/SchemaBuilder.d.ts
- packages/graphile-utils/__tests__/ExtendSchemaPlugin.test.js
- packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin.test.js.snap
- packages/graphile-utils/src/makeChangeNullabilityPlugin.ts
- packages/graphile-utils/src/makeExtendSchemaPlugin.ts
> feat(utils): makeExtendSchemaPlugin supports enums and default values

- packages/graphile-utils/__tests__/ExtendSchemaPlugin-pg.test.js
- packages/graphile-utils/__tests__/__snapshots__/ExtendSchemaPlugin-pg.test.js.snap
- packages/graphile-utils/__tests__/__snapshots__/makeAddPgTableConditionPlugin.test.js.snap
- packages/graphile-utils/__tests__/makeAddPgTableConditionPlugin.test.js
- packages/graphile-utils/__tests__/utils-schema.sql
- packages/graphile-utils/src/makeAddPgTableConditionPlugin.ts
Fixes graphile/postgraphile#1193
Even though it now has two tests, this plugin is still "experimental" status.
> fix(utils): make makeAddPgTableConditionPlugin work on simple collections

- .eslintrc.js
- packages/graphile-utils/src/gql.ts
- packages/graphile-utils/src/makeExtendSchemaPlugin.ts
- packages/graphile-utils/src/makeProcessSchemaPlugin.ts
- packages/graphile-utils/src/makeWrapResolversPlugin.ts
HT @ab-pm https://github.com/graphile/graphile-engine/pull/573/files#r353156177
> chore(lint): prevent `import * from 'graphql'` in plugins

- .gitignore
- packages/graphile-build-pg/package.json
- packages/graphile-build-pg/src/GraphQLJSON.ts
- packages/graphile-build-pg/src/QueryBuilder.ts
- packages/graphile-build-pg/src/withPgClient.ts
- packages/graphile-build-pg/tsconfig.json
- packages/graphile-build/package.json
- packages/graphile-build/src/Live.ts
- packages/graphile-build/src/SchemaBuilder.ts
- packages/graphile-build/src/index.ts
- packages/graphile-build/src/makeNewBuild.ts
- packages/graphile-build/src/plugins/AddQueriesToSubscriptionsPlugin.ts
- packages/graphile-build/src/plugins/MutationPlugin.ts
- packages/graphile-build/src/plugins/NodePlugin.ts
- packages/graphile-build/src/plugins/QueryPlugin.ts
- packages/graphile-build/src/plugins/StandardTypesPlugin.ts
- packages/graphile-build/src/plugins/SubscriptionPlugin.ts
- packages/graphile-build/src/plugins/SwallowErrorsPlugin.ts
- packages/graphile-build/tsconfig.json
- packages/graphile-utils/tsconfig.json
- packages/pg-pubsub/package.json
- packages/pg-pubsub/src/PgGenericSubscriptionPlugin.ts
- packages/pg-pubsub/tsconfig.json
- packages/pg-sql2/tsconfig.json
- packages/postgraphile-core/tsconfig.json
- packages/subscriptions-lds/tsconfig.json
- tsconfig.json
Implements project references and firms up a few more types. https://www.typescriptlang.org/docs/handbook/project-references.html
> chore: TypeScript project references; fix some types

- .eslintignore
- lerna.json
- packages/graphile-build-pg/src/QueryBuilder.ts
- packages/graphile-build-pg/src/plugins/PgBasicsPlugin.ts
- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.ts
- packages/graphile-build-pg/src/plugins/viaTemporaryTable.ts
- packages/graphile-build/src/SchemaBuilder.ts
- packages/jest-serializer-graphql-schema/README.md
- yarn.lock
Fixes #571
Was unable to push the lint fixes back to the @gastromatic repo, @michaelbeaumont. Seems I could only do edits on GitHub for some reason, but I needed to run commands locally.
> feat(watch): manual schema reload notification

- .flowconfig
- packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js
- packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js
- packages/graphile-utils/src/makePgSmartTagsPlugin.ts
Fixes https://github.com/graphile/postgraphile/issues/1207
> fix(smart-tags): enable using Smart Tags with @foreignKey and @primaryKey

- packages/graphile-build-pg/src/plugins/PgBackwardRelationPlugin.ts
- packages/postgraphile-core/__tests__/integration/schema/__snapshots__/omit-rename.omitstuff.test.js.snap
- packages/postgraphile-core/__tests__/integration/schema/omit-rename.omitstuff.test.js
> feat(omit) take "many" on constraints into account

- packages/pg-pubsub/src/PgSubscriptionResolverPlugin.ts
> feat(subscriptions): @pgSubscription now supports filter

- scripts/sponsors
Many thanks to our Featured Sponsors, past and present 😁💙
> sponsors: Update to Featured Sponsors

- README.md
- packages/graphile-build-pg/README.md
- packages/graphile-build/README.md
- packages/graphile-utils/README.md
- packages/graphql-parse-resolve-info/README.md
- packages/lds/README.md
- packages/pg-pubsub/README.md
- packages/pg-sql2/README.md
- packages/postgraphile-core/README.md
- packages/subscriptions-lds/README.md
- scripts/sponsors
An update for our Featured Sponsors for March. A warm welcome to our new Featured Sponsor, Postlight 💙
NB - doesn't handle individual project sponsors yet
> sponsorship: Update for March

- README.md
- SPONSORS.md
- packages/graphile-build-pg/README.md
- packages/graphile-build-pg/SPONSORS.md
- packages/graphile-build/README.md
- packages/graphile-build/SPONSORS.md
- packages/graphile-utils/README.md
- packages/graphile-utils/SPONSORS.md
- packages/graphql-parse-resolve-info/README.md
- packages/graphql-parse-resolve-info/SPONSORS.md
- packages/lds/README.md
- packages/lds/SPONSORS.md
- packages/pg-pubsub/README.md
- packages/pg-pubsub/SPONSORS.md
- packages/pg-sql2/README.md
- packages/pg-sql2/SPONSORS.md
- packages/postgraphile-core/README.md
- packages/postgraphile-core/SPONSORS.md
- packages/subscriptions-lds/README.md
- packages/subscriptions-lds/SPONSORS.md
Here is a sponsorship update for April, which includes a new sponsors.md file. This is the first time I've done this through a script so there are some formatting changes too. 
✨Thank you to each and every sponsor of Graphile, your donations are helping us to keep working during the pandemic ✨
> sponsorship: update sponsors for April ✨
